# Generated by Django 4.0.3 on 2025-01-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_size',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
