# Generated by Django 4.0.3 on 2025-01-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_max_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='max_size',
            field=models.PositiveIntegerField(default=2000000),
        ),
    ]
