# Generated by Django 4.2.20 on 2025-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupuser',
            name='can_view',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
