# Generated by Django 4.0.3 on 2025-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_max_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='passcode',
            field=models.CharField(max_length=2000),
        ),
    ]
