# Generated by Django 4.2.20 on 2025-05-02 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_remove_groupuser_can_view_groupuser_can_edit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="passcode",
        ),
    ]
