# Generated by Django 4.0.3 on 2025-01-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='passcode',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
