# Generated by Django 4.0.3 on 2025-01-30 18:44

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_file_extension_file_file_size_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=apps.files.models.content_file_name),
        ),
    ]
