# Generated by Django 4.2.20 on 2025-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('generate', 'Generate')], default='ready', max_length=20),
        ),
    ]
