# Generated by Django 4.2.18 on 2025-04-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_created_by'),
        ('files', '0004_alter_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='groups.group'),
        ),
    ]
