# Generated by Django 4.2.20 on 2025-04-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0004_file_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
